service: btb-service

frameworkVersion: ">=1.2.0 <2.0.0"

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - venv/**
    - __pycache__/**

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  runtime: python37
  project: team45
  region: asia-east2
  credentials: ./keyfile.json

functions:
  analysis:
    handler: analysis
    events:
      - http: path
  transaction:
    handler: transaction
    events:
      - http: path
  saving:
    handler: saving
    events:
      - http: path
